### PR TITLE
Create package.json

### PR DESCRIPTION
**Pull request by Jorropo**
That simplify lib download

### CODE REVIEW

**Comment by backkem** [comment]
Hi, sorry for the delay. I think we may need to put some more thought into this. 
- We're missing the `multiformats/go-multiaddr-dns` dependency.
- The `pions/webrtc` isn't under gx at the moment.
I'll have to get up-to-speed with gx and how it's used in libp2p to be able to get a better understanding of the best way forward.

**Comment by Jorropo** [comment]
@backkem 
Ok, I'll fix it when pions/webrtc is on gx, (if is it one day)

> Hi, sorry for the delay

Np, I do worst :)

**Comment by backkem** [comment]
Related discussion on gx vs go modules: ipfs/go-ipfs#5850

**Comment by backkem** [comment]
Closing in favor of go modules support added in 6639a4969691adeee12151f85f302dfc940e25c4.

**Pull request closed without merging**
